pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Cherukuri-Deepika/simple-java-maven-app.git', branch: 'master'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target\\surefire-reports\\*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat 'echo Simulating deployment step...'
            }
        }
    }
}
